/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    memes: Meme;
    'liquid-assets': LiquidAsset;
    media: Media;
    users: User;
    wallets: Wallet;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      wallets: 'wallets';
    };
  };
  collectionsSelect: {
    memes: MemesSelect<false> | MemesSelect<true>;
    'liquid-assets': LiquidAssetsSelect<false> | LiquidAssetsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    wallets: WalletsSelect<false> | WalletsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    provenance: Provenance;
    site: Site;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    provenance: ProvenanceSelect<false> | ProvenanceSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memes".
 */
export interface Meme {
  id: number;
  name: string;
  slug: string;
  creator?: string | null;
  dateAcquired?: string | null;
  isMemeNft?: boolean | null;
  isToken?: boolean | null;
  isPhysical?: boolean | null;
  knowYourMemeUrl?: string | null;
  provenanceUrl?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  thumbnail?: (number | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liquid-assets".
 */
export interface LiquidAsset {
  id: number;
  name: string;
  slug: string;
  creator?: string | null;
  ticker?: string | null;
  blockchain?: ('Ethereum' | 'Solana' | 'Base') | null;
  coingeckoUrl?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  thumbnail?: (number | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'editor' | 'dev' | 'writer' | 'user')[];
  wallets?: {
    docs?: (number | Wallet)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets".
 */
export interface Wallet {
  id: number;
  address: string;
  user: number | User;
  lastSignIn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'memes';
        value: number | Meme;
      } | null)
    | ({
        relationTo: 'liquid-assets';
        value: number | LiquidAsset;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'wallets';
        value: number | Wallet;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memes_select".
 */
export interface MemesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  creator?: T;
  dateAcquired?: T;
  isMemeNft?: T;
  isToken?: T;
  isPhysical?: T;
  knowYourMemeUrl?: T;
  provenanceUrl?: T;
  description?: T;
  image?: T;
  thumbnail?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "liquid-assets_select".
 */
export interface LiquidAssetsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  creator?: T;
  ticker?: T;
  blockchain?: T;
  coingeckoUrl?: T;
  description?: T;
  image?: T;
  thumbnail?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  wallets?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wallets_select".
 */
export interface WalletsSelect<T extends boolean = true> {
  address?: T;
  user?: T;
  lastSignIn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero?: {
    /**
     * ~text~ = dimmed, **text** = bold, new line = line break
     */
    title?: string | null;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    row1?: (number | Meme)[] | null;
    row2?: (number | Meme)[] | null;
  };
  explainer?: {
    label?: string | null;
    cards?:
      | {
          category?: string | null;
          /**
           * ~text~ = dimmed, **text** = bold, new line = line break
           */
          title?: string | null;
          subtitle?: string | null;
          body?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          link?: {
            label?: string | null;
            href?: string | null;
          };
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  treasury?: {
    label?: string | null;
    nftsLabel?: string | null;
    tokensLabel?: string | null;
  };
  manifesto?: {
    label?: string | null;
    /**
     * ~text~ = dimmed, **text** = bold, new line = line break
     */
    title?: string | null;
    items?:
      | {
          /**
           * ~text~ = dimmed, **text** = bold, new line = line break
           */
          title?: string | null;
          body?: string | null;
          id?: string | null;
        }[]
      | null;
    link?: {
      label?: string | null;
      href?: string | null;
    };
  };
  creators?: {
    label?: string | null;
    category?: string | null;
    /**
     * ~text~ = dimmed, **text** = bold, new line = line break
     */
    title?: string | null;
    subtitle?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    link?: {
      label?: string | null;
      href?: string | null;
    };
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provenance".
 */
export interface Provenance {
  id: number;
  hero?: {
    /**
     * ~text~ = dimmed, **text** = bold, new line = line break
     */
    title?: string | null;
    subtitle?: string | null;
    image?: (number | null) | Media;
  };
  mission?: {
    label?: string | null;
    blocks?:
      | {
          /**
           * ~text~ = dimmed, **text** = bold, new line = line break
           */
          title?: string | null;
          body?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
    link?: {
      /**
       * ~text~ = dimmed, **text** = bold, new line = line break
       */
      label?: string | null;
      href?: string | null;
    };
  };
  records?: {
    label?: string | null;
    link?: {
      label?: string | null;
      href?: string | null;
    };
    note?: string | null;
  };
  feature?: {
    label?: string | null;
    category?: string | null;
    /**
     * ~text~ = dimmed, **text** = bold, new line = line break
     */
    title?: string | null;
    subtitle?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    link?: {
      label?: string | null;
      href?: string | null;
    };
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  /**
   * Meta description + footer tagline
   */
  description?: string | null;
  ogImage?: (number | null) | Media;
  nav?: {
    cta?: {
      label?: string | null;
      href?: string | null;
    };
    socials?:
      | {
          platform: 'x' | 'discord' | 'telegram' | 'dexscreener';
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    label?: string | null;
    /**
     * ~text~ = dimmed, **text** = bold, new line = line break
     */
    title?: string | null;
    link?: {
      label?: string | null;
      href?: string | null;
    };
  };
  footer?: {
    orgLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    /**
     * "Memes" column, in order
     */
    memes?: (number | Meme)[] | null;
    tokenLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    socialLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    contract?: string | null;
    copyright?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        row1?: T;
        row2?: T;
      };
  explainer?:
    | T
    | {
        label?: T;
        cards?:
          | T
          | {
              category?: T;
              title?: T;
              subtitle?: T;
              body?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              image?: T;
              id?: T;
            };
      };
  treasury?:
    | T
    | {
        label?: T;
        nftsLabel?: T;
        tokensLabel?: T;
      };
  manifesto?:
    | T
    | {
        label?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  creators?:
    | T
    | {
        label?: T;
        category?: T;
        title?: T;
        subtitle?: T;
        body?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provenance_select".
 */
export interface ProvenanceSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
      };
  mission?:
    | T
    | {
        label?: T;
        blocks?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  records?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        note?: T;
      };
  feature?:
    | T
    | {
        label?: T;
        category?: T;
        title?: T;
        subtitle?: T;
        body?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  description?: T;
  ogImage?: T;
  nav?:
    | T
    | {
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        socials?:
          | T
          | {
              platform?: T;
              href?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        label?: T;
        title?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  footer?:
    | T
    | {
        orgLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        memes?: T;
        tokenLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        socialLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        contract?: T;
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}